language: java
jdk:
  - oraclejdk8
jobs:
  include:
      script: licenses-collector-service/gradlew -b licenses-collector-service/build.gradle test iT
    - stage: Package
      script: licenses-collector-service/gradlew -b licenses-collector-service/build.gradle a
  include:
    - stage: Dependency security checks
      script: travis_wait 30 licenses-collector-service/gradlew -b licenses-collector-service/build.gradle depChe      