language: java
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: test
      script: licenses-collector-service/gradlew -b licenses-collector-service/build.gradle test It
    - stage: Dependency security checks
      script: licenses-collector-service/gradlew -b licenses-collector-service/build.gradle depChe      
    - stage: Package
      script: licenses-collector-service/gradlew -b licenses-collector-service/build.gradle a
